version: '3.0'

services:
  media:
    container_name: media
    image: kurento/kurento-media-server:latest-xenial
    restart: on-failure
    ports:
    - "8888:8888"
    - "8433:8433"
    - "49152-65535:49152-65535/udp"
    volumes:
    - './docker/config/kurento:/etc/kurento'
    - './docker/files:/files'
    - './docker/files:/tmp'

    depends_on:
    - coturn
    network_mode: "host"
    # environment:
    #   GST_DEBUG: 7

  coturn:
    container_name: coturn
    image: kurento/coturn-auth
    restart: on-failure
    ports:
      - 3478:3478
    environment:
      LISTENING_PORT: 3478
      USER: ninefingers
      REALM: kurento.org
      PASSWORD: youhavetoberealistic
    volumes:
      - ./docker/config/coturn/turnserver.conf:/etc/turnserver.conf
    network_mode: "host"

  web:
    image: node:carbon
    container_name: kos
    command: 'npm run inspect'
    working_dir: /usr/app
    volumes:
    - './:/usr/app'
    - './files:/files'
    ports:
    - "443:3001"
    - "80:3000"
    - "5858:5858"
    environment:
      NODE_ENV: "development"